// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { commanderError, error, stringArray, zodError } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errorsUtils: {
		/**
		 * [​{​n​a​m​e​}​]​{​t​y​p​e​|​c​a​p​i​t​a​l​i​z​e​}​:
		 * @param {string} name
		 * @param {string} type
		 */
		header: RequiredParams<'name' | 'type|capitalize'>
	}
	errors: {
		snapshot: {
			meta: {
				/**
				 * S​n​a​p​s​h​o​t​ ​m​e​t​a​ ​n​o​t​ ​f​o​u​n​d​.
				 */
				notFound: string
				/**
				 * S​n​a​p​s​h​o​t​ ​m​e​t​a​ ​i​s​ ​n​o​t​ ​l​o​c​k​e​d​.
				 */
				notLocked: string
				/**
				 * S​n​a​p​s​h​o​t​ ​m​e​t​a​ ​i​s​ ​n​o​t​ ​u​n​l​o​c​k​e​d​.
				 */
				notUnlocked: string
				/**
				 * I​n​v​a​l​i​d​ ​d​i​g​e​s​t​e​r​ ​k​e​y​.
				 */
				invalidDigest: string
				/**
				 * T​h​e​ ​s​n​a​p​s​h​o​t​ ​m​e​t​a​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​.
				 */
				missmatch: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​n​a​p​s​h​o​t​ ​m​e​t​a​.
				 */
				failedToCreate: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​s​n​a​p​s​h​o​t​ ​m​e​t​a​.
				 */
				failedToLoad: string
			}
			source: {
				/**
				 * S​o​u​r​c​e​ ​n​o​t​ ​f​o​u​n​d​.
				 */
				notFound: string
				/**
				 * S​p​e​c​n​o​v​a​ ​s​o​u​r​c​e​ ​m​u​s​t​ ​b​e​ ​l​o​a​d​e​d​ ​f​r​o​m​ ​a​ ​m​e​t​a​ ​f​i​l​e​.
				 */
				internalFailedToLoad: string
			}
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​{​0​}​{​0​}​.
			 * @param {string | stringArray} 0
			 */
			failedToSave: RequiredParams<'0' | '0'>
		}
		reference: {
			parse: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​p​a​r​s​e​ ​s​o​u​r​c​e​.
				 */
				failedToParse: string
				/**
				 * I​n​v​a​l​i​d​ ​f​i​l​e​ ​e​x​t​e​n​s​i​o​n​.​ ​S​u​p​p​o​r​t​e​d​ ​e​x​t​e​n​s​i​o​n​s​:​ ​{​e​x​t​e​n​s​i​o​n​}​.
				 * @param {stringArray} extension
				 */
				invalidFileExtension: RequiredParams<'extension'>
				/**
				 * N​o​ ​r​e​s​u​l​t​ ​f​o​u​n​d​.
				 */
				noResult: string
			}
		}
		parser: {
			/**
			 * U​n​k​n​o​w​n​ ​c​o​m​m​a​n​d​.
			 */
			unknownCommand: string
			/**
			 * N​o​ ​h​a​n​d​l​e​r​ ​f​o​u​n​d​.
			 */
			noHandlerFound: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​e​x​e​c​u​t​e​ ​"​{​n​a​m​e​}​"​ ​c​o​m​m​a​n​d​ ​f​o​r​ ​e​l​e​m​e​n​t​ ​"​{​e​l​e​m​e​n​t​}​.​"
			 * @param {string} element
			 * @param {string} name
			 */
			failedToExecute: RequiredParams<'element' | 'name'>
			refractor: {
				/**
				 * N​o​ ​r​e​f​r​a​c​t​o​r​ ​f​o​u​n​d​.
				 */
				noRefractorFound: string
			}
		}
		unimplimented: {
			/**
			 * U​n​k​n​o​w​n​ ​e​r​r​o​r
			 */
			unknownError: string
			/**
			 * {​0​|​p​r​i​n​t​E​r​r​o​r​}
			 * @param {error} 0
			 */
			fromError: RequiredParams<'0|printError'>
		}
		typesafe_i18n: {
			/**
			 * {​{​i​1​8​n​_​i​n​v​a​l​i​d​_​p​a​r​a​m​}​}
			 */
			'invalid-formatter-param': string
		}
		config: {
			/**
			 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​i​s​ ​n​o​t​ ​l​o​a​d​e​d​.
			 */
			notLoaded: string
			adapter: {
				/**
				 * G​e​n​e​r​a​t​i​o​n​ ​i​s​ ​n​o​t​ ​i​m​p​l​e​m​e​n​t​e​d
				 */
				generateNotImplemented: string
			}
		}
		extracter: {
			/**
			 * N​o​ ​h​a​n​d​l​e​r​ ​f​o​u​n​d​.
			 */
			noHandlerFound: string
		}
		zod: {
			/**
			 * {​0​|​p​r​i​n​t​Z​o​d​E​r​r​o​r​}
			 * @param {zodError} 0
			 */
			fromError: RequiredParams<'0|printZodError'>
		}
		cli: {
			/**
			 * {​0​|​p​r​i​n​t​C​o​m​m​a​n​d​e​r​E​r​r​o​r​}
			 * @param {commanderError} 0
			 */
			fromError: RequiredParams<'0|printCommanderError'>
		}
	}
}

export type TranslationFunctions = {
	errorsUtils: {
		/**
		 * [{name}]{type|capitalize}:
		 */
		header: (arg: { name: string, type: string }) => LocalizedString
	}
	errors: {
		snapshot: {
			meta: {
				/**
				 * Snapshot meta not found.
				 */
				notFound: () => LocalizedString
				/**
				 * Snapshot meta is not locked.
				 */
				notLocked: () => LocalizedString
				/**
				 * Snapshot meta is not unlocked.
				 */
				notUnlocked: () => LocalizedString
				/**
				 * Invalid digester key.
				 */
				invalidDigest: () => LocalizedString
				/**
				 * The snapshot meta does not match.
				 */
				missmatch: () => LocalizedString
				/**
				 * Failed to create snapshot meta.
				 */
				failedToCreate: () => LocalizedString
				/**
				 * Failed to load snapshot meta.
				 */
				failedToLoad: () => LocalizedString
			}
			source: {
				/**
				 * Source not found.
				 */
				notFound: () => LocalizedString
				/**
				 * Specnova source must be loaded from a meta file.
				 */
				internalFailedToLoad: () => LocalizedString
			}
			/**
			 * Failed to save {0}{0}.
			 */
			failedToSave: (arg0: string | stringArray) => LocalizedString
		}
		reference: {
			parse: {
				/**
				 * Failed to parse source.
				 */
				failedToParse: () => LocalizedString
				/**
				 * Invalid file extension. Supported extensions: {extension}.
				 */
				invalidFileExtension: (arg: { extension: stringArray }) => LocalizedString
				/**
				 * No result found.
				 */
				noResult: () => LocalizedString
			}
		}
		parser: {
			/**
			 * Unknown command.
			 */
			unknownCommand: () => LocalizedString
			/**
			 * No handler found.
			 */
			noHandlerFound: () => LocalizedString
			/**
			 * Failed to execute "{name}" command for element "{element}."
			 */
			failedToExecute: (arg: { element: string, name: string }) => LocalizedString
			refractor: {
				/**
				 * No refractor found.
				 */
				noRefractorFound: () => LocalizedString
			}
		}
		unimplimented: {
			/**
			 * Unknown error
			 */
			unknownError: () => LocalizedString
			/**
			 * {0|printError}
			 */
			fromError: (arg0: error) => LocalizedString
		}
		typesafe_i18n: {
			/**
			 * {{i18n_invalid_param}}
			 */
			'invalid-formatter-param': (arg0: number | string | boolean) => LocalizedString
		}
		config: {
			/**
			 * Configuration is not loaded.
			 */
			notLoaded: () => LocalizedString
			adapter: {
				/**
				 * Generation is not implemented
				 */
				generateNotImplemented: () => LocalizedString
			}
		}
		extracter: {
			/**
			 * No handler found.
			 */
			noHandlerFound: () => LocalizedString
		}
		zod: {
			/**
			 * {0|printZodError}
			 */
			fromError: (arg0: zodError) => LocalizedString
		}
		cli: {
			/**
			 * {0|printCommanderError}
			 */
			fromError: (arg0: commanderError) => LocalizedString
		}
	}
}

export type Formatters = {
	capitalize: (value: string) => unknown
	printCommanderError: (value: commanderError) => unknown
	printError: (value: error) => unknown
	printZodError: (value: zodError) => unknown
}
