// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errorsUtils: {
		/**
		 * [​{​n​a​m​e​}​]​{​t​y​p​e​|​c​a​p​i​t​a​l​i​z​e​}​:
		 * @param {string} name
		 * @param {string} type
		 */
		header: RequiredParams<'name' | 'type|capitalize'>
	}
	errors: {
		'default': {
			/**
			 * {​0​|​e​r​r​o​r​}
			 * @param {unknown} 0
			 */
			fromError: RequiredParams<'0|error'>
		}
		typesafe_i18n: {
			/**
			 * {​{​{​i​1​8​n​_​i​n​v​_​p​a​r​a​m​}​}​}
			 */
			'invalid-formatter-param': string
		}
		config: {
			/**
			 * I​n​v​a​l​i​d​ ​a​d​a​p​t​e​r
			 */
			'invalid-adapter': string
		}
		zod: {
			/**
			 * {​0​|​z​o​d​P​r​e​t​t​i​f​i​e​d​E​r​r​o​r​}
			 * @param {unknown} 0
			 */
			fromError: RequiredParams<'0|zodPrettifiedError'>
		}
	}
}

export type TranslationFunctions = {
	errorsUtils: {
		/**
		 * [{name}]{type|capitalize}:
		 */
		header: (arg: { name: string, type: string }) => LocalizedString
	}
	errors: {
		'default': {
			/**
			 * {0|error}
			 */
			fromError: (arg0: unknown) => LocalizedString
		}
		typesafe_i18n: {
			/**
			 * {{{i18n_inv_param}}}
			 */
			'invalid-formatter-param': (arg0: number | string | boolean) => LocalizedString
		}
		config: {
			/**
			 * Invalid adapter
			 */
			'invalid-adapter': () => LocalizedString
		}
		zod: {
			/**
			 * {0|zodPrettifiedError}
			 */
			fromError: (arg0: unknown) => LocalizedString
		}
	}
}

export type Formatters = {
	capitalize: (value: string) => unknown
	error: (value: unknown) => unknown
	zodPrettifiedError: (value: unknown) => unknown
}
